#!/usr/bin/env python3
"""Generate deterministic data for the parameterized CSR scatter test.

The output defines two assembly macros:
  CSR_DATA   - one shuffled 8-byte entry for every PU in the system
  REF_RESULT - XOR of the low 32 bits of sub_idx * weight for every entry

Every MC image contains the same CSR_DATA table. Each MemIf broadcasts only to
its own PU zone, so every PU receives exactly its one matching entry.
"""

import argparse
import random


SEED = 42


def mul32(a, b):
    """Return the low 32 bits of an unsigned multiplication."""
    return (a * b) & 0xFFFFFFFF


def format_word(pu_id, sub_idx):
    """Pack the little-endian CSR key as (sub_idx << 16) | pu_id."""
    return (sub_idx << 16) | pu_id


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--num-pu", type=int, required=True)
    parser.add_argument("--line-bytes", type=int, required=True)
    parser.add_argument("output")
    args = parser.parse_args()

    if not 1 <= args.num_pu <= 0xFFFF:
        parser.error("--num-pu must fit the 16-bit broadcast PU field")
    if args.line_bytes < 8 or args.line_bytes & (args.line_bytes - 1):
        parser.error("--line-bytes must be a power of two of at least 8")

    # Generate one deterministic, shuffled entry for each legal destination PU.
    rng = random.Random(SEED)
    entries = []
    for pu_id in range(1, args.num_pu + 1):
        entries.append((pu_id, rng.randint(0, 0xFFFF), rng.randint(0, 0xFFFFFFFF)))
    rng.shuffle(entries)

    # Each entry is delivered exactly once across all MemIf zones.
    ref_xor = 0
    for _, sub_idx, weight in entries:
        ref_xor ^= mul32(sub_idx, weight)

    # Align the common table to the target's external-memory transaction size.
    lines = [
        "# AUTO-GENERATED by gen_csr_data.py - do not edit",
        f"# CSR scatter test data for {args.num_pu} PUs",
        "",
        ".macro CSR_DATA",
        f".balign {args.line_bytes}",
        ".globl csr_data",
        "csr_data:",
    ]
    for pu_id, sub_idx, weight in entries:
        word0 = format_word(pu_id, sub_idx)
        lines.append(
            f"  .word 0x{word0:08X}, 0x{weight:08X}   # PU {pu_id}, sub_idx=0x{sub_idx:04X}"
        )
    lines.extend([
        ".globl csr_data_end",
        "csr_data_end:",
        ".endm",
        "",
        ".macro REF_RESULT",
        f"  .word 0x{ref_xor:08X}",
        ".endm",
        "",
    ])

    with open(args.output, "w", encoding="ascii") as output:
        output.write("\n".join(lines))

    print(f"Generated {args.output}")
    print(f"  PUs: {args.num_pu}")
    print(f"  entries: {len(entries)}")
    print(f"  line bytes: {args.line_bytes}")
    print(f"  REF_RESULT: 0x{ref_xor:08X}")


if __name__ == "__main__":
    main()
