#!/usr/bin/env python3
"""Generate random CSR scatter test data for csr_scatter_test (64 PU, 2 MC).

Produces sys/csr_scatter_data.S with three macros:
  CSR0 — data for dram.0 (64 entries, shuffled)
  CSR1 — data for dram.1 (64 entries, shuffled)
  REF_RESULT — expected global XOR of (sub_idx * weight) for reachable entries

MC0 broadcasts reach PUs 1-32.  MC1 broadcasts reach PUs 33-64.
Entries targeting unreachable PUs are still present but won't be dispatched.
"""

import random
import struct
import sys

NUM_PU = 64
PUS_PER_MC = 32  # MC0: PUs 1-32, MC1: PUs 33-64

SEED = 42
random.seed(SEED)


def rand_u16():
    return random.randint(0, 0xFFFF)


def rand_u32():
    return random.randint(0, 0xFFFFFFFF)


def mul32(a, b):
    """32-bit unsigned multiplication (low 32 bits)."""
    return (a * b) & 0xFFFFFFFF


def gen_entries():
    """Generate 64 CSR entries: one per PU (1..64), random sub_idx and weight, shuffled."""
    entries = []
    for pu_id in range(1, NUM_PU + 1):
        sub_idx = rand_u16()
        weight = rand_u32()
        entries.append((pu_id, sub_idx, weight))
    random.shuffle(entries)
    return entries


def compute_ref_xor(csr0_entries, csr1_entries):
    """Compute global XOR of (sub_idx * weight) for reachable entries only."""
    xor_acc = 0
    # MC0 reaches PUs 1-32
    for pu_id, sub_idx, weight in csr0_entries:
        if 1 <= pu_id <= PUS_PER_MC:
            xor_acc ^= mul32(sub_idx, weight)
    # MC1 reaches PUs 33-64
    for pu_id, sub_idx, weight in csr1_entries:
        if PUS_PER_MC + 1 <= pu_id <= NUM_PU:
            xor_acc ^= mul32(sub_idx, weight)
    return xor_acc


def format_word(pu_id, sub_idx):
    """CSR entry word0: (sub_idx << 16) | pu_id.  byte[0-1]=pu_id, byte[2-3]=sub_idx."""
    return (sub_idx << 16) | pu_id


def emit_asm(csr0, csr1, ref_xor, outpath):
    lines = []
    lines.append("# AUTO-GENERATED by gen_csr_data.py — do not edit")
    lines.append("# CSR scatter test data for 64 PU, 2 MC")
    lines.append("")

    # CSR0 macro
    lines.append(".macro CSR0")
    lines.append(".balign 32")
    lines.append(".globl csr0")
    lines.append("csr0:")
    for pu_id, sub_idx, weight in csr0:
        word0 = format_word(pu_id, sub_idx)
        lines.append(f"  .word 0x{word0:08X}, 0x{weight:08X}   # PU {pu_id}, sub_idx=0x{sub_idx:04X}")
    lines.append(".globl csr0_end")
    lines.append("csr0_end:")
    lines.append(".endm")
    lines.append("")

    # CSR1 macro
    lines.append(".macro CSR1")
    lines.append(".balign 32")
    lines.append(".globl csr1")
    lines.append("csr1:")
    for pu_id, sub_idx, weight in csr1:
        word0 = format_word(pu_id, sub_idx)
        lines.append(f"  .word 0x{word0:08X}, 0x{weight:08X}   # PU {pu_id}, sub_idx=0x{sub_idx:04X}")
    lines.append(".globl csr1_end")
    lines.append("csr1_end:")
    lines.append(".endm")
    lines.append("")

    # REF_RESULT macro
    lines.append(".macro REF_RESULT")
    lines.append(f"  .word 0x{ref_xor:08X}")
    lines.append(".endm")
    lines.append("")

    with open(outpath, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated {outpath}")
    print(f"  CSR0: {len(csr0)} entries")
    print(f"  CSR1: {len(csr1)} entries")
    print(f"  REF_RESULT: 0x{ref_xor:08X}")


def main():
    csr0 = gen_entries()
    csr1 = gen_entries()
    ref_xor = compute_ref_xor(csr0, csr1)
    outpath = sys.argv[1] if len(sys.argv) > 1 else "sys/csr_scatter_data.S"
    emit_asm(csr0, csr1, ref_xor, outpath)


if __name__ == "__main__":
    main()
