/*
 * SNN initialization — C implementation
 *
 * Called from snn_main.S after stack setup.
 * Reads the SPM init descriptor from DRAM, copies neuron data to SPM,
 * and runs the current-based init loop (state += input, clear input).
 * Conductance images already contain their pre-simulated ge/gi/v state.
 *
 * Returns hartid.
 *
 * DRAM header (at 0x80000000):
 *   word0: jump instruction
 *   word1: offset to SPM init section (from start of image)
 *   word2: num_mc
 *   word3: num_pu
 *
 * SPM init section layout:
 *   Per-PU descriptor (8 bytes each): offset (relative to section start), size
 *   Then: SPM data blobs (one full SPM image per PU)
 *
 * SPM tail descriptor (generated by datagen, at end of SPM):
 *   end - 0x14: decay (FP32)
 *   end - 0x10: threshold (FP32)
 *   end - 0x0C: type (0)
 *   end - 0x08: stride (bytes)
 *   end - 0x04: neuron count
 *   end - 0x24: expected post-timestep checksum
 */

#define SPM_BASE    0x20000000u
#define SPM_SIZE    16384u
#define DRAM_BASE   0x80000000u
#define STOP_ADDR   0x40000000u
#define PRINT_PORT  0x4000000Cu

#define AC_CTRL_CSR  0x730
#define AC_GBASE_CSR 0x731
#define AC_SBASE_CSR 0x732
#define AC_LEN_CSR   0x733
#define MEM_LINE_SIZE 64u

static inline unsigned int csrr_f14(void) {
    unsigned int id;
    __asm__ volatile ("csrr %0, 0xF14" : "=r"(id));
    return id;
}

static inline void async_copy(unsigned int src, unsigned int dst,
                              unsigned int size) {
    __asm__ volatile ("csrw 0x731, %0" :: "r"(src) : "memory");
    __asm__ volatile ("csrw 0x732, %0" :: "r"(dst) : "memory");
    __asm__ volatile ("csrw 0x733, %0" :: "r"(size) : "memory");
    __asm__ volatile ("csrw 0x730, zero" ::: "memory");

    unsigned int remaining;
    do {
        __asm__ volatile ("csrr %0, 0x730" : "=r"(remaining) :: "memory");
    } while (remaining != 0);
}

static void halt(unsigned int code) {
    *(volatile unsigned int *)STOP_ADDR = code;
    while (1) __asm__ volatile ("wfi");
}

unsigned int snn_init(void) {
    unsigned int hartid = csrr_f14();

    volatile unsigned int *header = (volatile unsigned int *)DRAM_BASE;
    unsigned int spm_init_offset = header[1];
    unsigned int num_pu = header[3];

    if (hartid == 0 || hartid > num_pu)
        halt(0xbad10000u | hartid);

    /* Descriptor table starts at DRAM_BASE + spm_init_offset */
    volatile unsigned int *section = (volatile unsigned int *)(DRAM_BASE + spm_init_offset);
    /* Each descriptor is 8 bytes (2 words): offset, size */
    unsigned int desc_idx = hartid - 1;
    unsigned int data_offset = section[desc_idx * 2];      /* relative to section start */
    unsigned int data_size   = section[desc_idx * 2 + 1];

    unsigned int src = DRAM_BASE + spm_init_offset + data_offset;

    if ((src & (MEM_LINE_SIZE - 1)) != 0 ||
        (data_size & (MEM_LINE_SIZE - 1)) != 0)
        halt(0xbad30000u | hartid);

    /* Copy the complete SPM image from DRAM. */
    async_copy(src, SPM_BASE, data_size);

    /* Read metadata from tail */
    unsigned int nn_count = *(volatile unsigned int *)(SPM_BASE + SPM_SIZE - 4);
    unsigned int stride   = *(volatile unsigned int *)(SPM_BASE + SPM_SIZE - 8);

    if (stride == 0)
        halt(0xbad20000u | hartid);

#ifndef CONDUCTANCE
    /* Init loop: state += input, clear input */
    unsigned int nn_end = SPM_BASE + nn_count * stride;
    for (unsigned int addr = SPM_BASE; addr < nn_end; addr += stride) {
        volatile unsigned int *st = (volatile unsigned int *)addr;
        volatile unsigned int *input = (volatile unsigned int *)(addr + 4);
        unsigned int s = *st;
        unsigned int inp = *input;
        unsigned int result;
        __asm__ volatile (
            "mv t0, %1\n\t"
            "mv t1, %2\n\t"
            "fadd.s f5, f5, f6\n\t"
            "mv %0, t0\n\t"
            : "=r"(result)
            : "r"(s), "r"(inp)
            : "t0", "t1"
        );
        *st = result;
        *input = 0;
    }
#endif

    return hartid;
}
