#!/usr/bin/env python3
"""Generate system_config.h and hard_backend.h from System.config.json."""
import sys, os, json

config_json = sys.argv[1]  # Path to System.config.json
outdir = sys.argv[2]       # Output directory

with open(config_json) as f:
    cfg = json.load(f)

num_pu = cfg["numPU"]
num_mc = cfg["numMC"]
core = cfg["core"]

# ---- system_config.h (legacy, kept for soft backend's SYSTEM_CONFIG) ----
with open(os.path.join(outdir, "system_config.h"), "w") as f:
    f.write("// Auto-generated by gen_system_header.py — do not edit\n")
    f.write("#pragma once\n")
    f.write("#include <cstdint>\n\n")

    # Data constants used by soft backend (no struct definitions — those live in system.h)
    sizes = ", ".join(f"0x{int(s, 16):x}" if isinstance(s, str) else f"0x{s:x}" for s in core["memCtrlSizes"])
    init_vec = int(core["initVec"], 16) if isinstance(core["initVec"], str) else core["initVec"]

    f.write(f"inline constexpr int SYSTEM_NUM_PU = {num_pu};\n")
    f.write(f"inline constexpr int SYSTEM_NUM_MC = {num_mc};\n")
    f.write(f"inline constexpr int SYSTEM_NUM_MEM_CTRL = {len(core['memCtrlSizes'])};\n")
    f.write(f"inline constexpr uint64_t SYSTEM_MC_SIZES[] = {{{sizes}}};\n")
    f.write(f"inline constexpr uint64_t SYSTEM_INIT_VEC = 0x{init_vec:x};\n")
    f.write(f"inline constexpr int SYSTEM_ICACHE_LINES = {core['iCacheLines']};\n")
    f.write(f"inline constexpr int SYSTEM_ICACHE_BLOCK_SIZE = {core['iCacheBlockSize']};\n")
    f.write(f"inline constexpr int SYSTEM_ICACHE_ASSOC = {core['iCacheAssoc']};\n")
    f.write(f"inline constexpr int SYSTEM_MEM_BUS_WIDTH = {core['memBusWidth']};\n")
    f.write(f"inline constexpr int SYSTEM_SCRATCHPAD_SIZE = {core['scratchpadSize']};\n")
    f.write(f"inline constexpr bool SYSTEM_USE_FPU = {'true' if core['useFPU'] else 'false'};\n")
    f.write(f"inline constexpr int SYSTEM_PIPE_CNT = {core['pipeCnt']};\n\n")

    # PU core accessor for SPM preloading (legacy)
    f.write("// Verilator PU core accessors for SPM preloading\n")
    f.write("#define SYSTEM_PU_CASE_ENTRIES \\\n")
    for i in range(1, num_pu + 1):
        f.write(f"    PU_CASE({i});")
        if i < num_pu:
            f.write(" \\")
        f.write("\n")

# ---- hard_backend.h (generated adapter implementing SystemBackend) ----
with open(os.path.join(outdir, "hard_backend.h"), "w") as f:
    f.write("// Auto-generated by gen_system_header.py — do not edit\n")
    f.write("#pragma once\n\n")
    f.write('#include "system.h"\n')
    f.write('#include "sys_verilated/sys_rtl.h"\n')
    f.write('#include <memory>\n')
    f.write('#include <cstring>\n')
    f.write('#include <cstdlib>\n')
    f.write('#include <iostream>\n')
    f.write('#include <vector>\n')
    f.write('#include <verilated.h>\n')
    f.write('#include <verilated_fst_c.h>\n')
    f.write('\n')

    f.write(f"static constexpr int HARD_NUM_PU = {num_pu};\n")
    f.write(f"static constexpr int HARD_NUM_MC = {num_mc};\n")
    mc_sizes_list = ", ".join(
        f"0x{int(s, 16):x}" if isinstance(s, str) else f"0x{s:x}"
        for s in core["memCtrlSizes"]
    )
    f.write(f"static constexpr uint64_t HARD_MC_SIZES[] = {{{mc_sizes_list}}};\n")
    f.write(f"static constexpr uint64_t HARD_RESET_LENGTH = 10;\n\n")

    # MemPort struct
    f.write("struct HardMemPort {\n")
    f.write("    uint8_t *req_valid;\n")
    f.write("    uint8_t *req_ready;\n")
    f.write("    uint8_t *req_id;\n")
    f.write("    uint32_t *req_addr;\n")
    f.write("    uint32_t *req_wdata; // WData[8]\n")
    f.write("    uint32_t *req_wbe;\n")
    f.write("    uint8_t *req_size;\n")
    f.write("    uint8_t *req_write;\n")
    f.write("    uint8_t *resp_valid;\n")
    f.write("    uint8_t *resp_id;\n")
    f.write("    uint32_t *resp_rdata; // WData[8]\n")
    f.write("};\n\n")

    f.write("class HardSystemBackend : public SystemBackend {\n")
    f.write("public:\n")
    f.write("    std::unique_ptr<sys_rtl> sys;\n")
    f.write("    uint64_t cycle_ = 0;\n")
    f.write(f"    HardMemPort mem_ports[{num_mc}];\n")
    f.write("    VerilatedFstC *tracer_ = nullptr;\n")
    f.write("    bool tracing_ = false;\n")
    f.write("    uint64_t trace_start_ = 0;\n\n")

    # Constructor
    f.write("    HardSystemBackend() {\n")
    f.write('        sys.reset(new sys_rtl("system"));\n')
    for i in range(num_mc):
        f.write(f"        mem_ports[{i}].req_valid = &sys->io_mem_{i}_req_valid;\n")
        f.write(f"        mem_ports[{i}].req_ready = &sys->io_mem_{i}_req_ready;\n")
        f.write(f"        mem_ports[{i}].req_id = &sys->io_mem_{i}_req_bits_id;\n")
        f.write(f"        mem_ports[{i}].req_addr = &sys->io_mem_{i}_req_bits_addr;\n")
        f.write(f"        mem_ports[{i}].req_wdata = sys->io_mem_{i}_req_bits_wdata;\n")
        f.write(f"        mem_ports[{i}].req_wbe = &sys->io_mem_{i}_req_bits_wbe;\n")
        f.write(f"        mem_ports[{i}].req_size = &sys->io_mem_{i}_req_bits_size;\n")
        f.write(f"        mem_ports[{i}].req_write = &sys->io_mem_{i}_req_bits_write;\n")
        f.write(f"        mem_ports[{i}].resp_valid = &sys->io_mem_{i}_resp_valid;\n")
        f.write(f"        mem_ports[{i}].resp_id = &sys->io_mem_{i}_resp_bits_id;\n")
        f.write(f"        mem_ports[{i}].resp_rdata = sys->io_mem_{i}_resp_bits_rdata;\n")
    f.write("    }\n\n")

    f.write("    ~HardSystemBackend() override { sys->final(); }\n\n")

    f.write("    void attachTrace(VerilatedFstC *t, int depth) {\n")
    f.write("        tracing_ = t != nullptr;\n")
    f.write("        tracer_ = t;\n")
    f.write("        // Trace registration is done once at top-level via the\n")
    f.write("        // shared VerilatedContext, so we don't call sys->trace() here.\n")
    f.write("    }\n\n")
    f.write("    void setTraceStart(uint64_t t) { trace_start_ = t; }\n\n")

    # config()
    f.write("    SystemConfig config() const override {\n")
    f.write("        SystemConfig cfg;\n")
    f.write(f"        cfg.numPU = HARD_NUM_PU;\n")
    f.write(f"        cfg.numMC = HARD_NUM_MC;\n")
    f.write(f"        for (int i = 0; i < HARD_NUM_MC; ++i)\n")
    f.write(f"            cfg.core.mcSizes.push_back(HARD_MC_SIZES[i]);\n")
    f.write("        return cfg;\n")
    f.write("    }\n\n")

    # peek(): post-(K-1)-posedge, pre-K-negedge logic; emit current request.
    f.write("""    void peek(uint64_t cycle, std::vector<MemBusOut *> out) override {
        cycle_ = cycle;
        static constexpr int MEM_BUS_WORDS = MEM_BUS_WIDTH / 32;
        if ((int)out.size() != HARD_NUM_MC + 1) {
            std::cerr << "[Hard] peek: out vector size mismatch" << std::endl;
            std::abort();
        }
        // Reset deassertion is synchronous: at the start of cycle K (just after
        // posedge K-1), we set sys->reset to its value for cycle K.
        sys->reset = (cycle_ <= HARD_RESET_LENGTH);
        // Eval to propagate reset value into combinational outputs (req signals).
        sys->eval();

        // Capture MC requests presented on the bus at cycle K.
        for (int mc = 0; mc < HARD_NUM_MC; ++mc) {
            auto &p = mem_ports[mc];
            if (*p.req_valid) {
                GlobalMemReq req{};
                req.id = *p.req_id;
                req.addr = *p.req_addr;
                req.write = *p.req_write;
                req.size = *p.req_size;
                req.wbe = *p.req_wbe;
                std::memcpy(req.wdata.data(), p.req_wdata, MEM_BUS_WORDS * 4);
                out[mc + 1]->req = req;
            } else {
                out[mc + 1]->req = std::nullopt;
            }
        }
        if (sys->io_periph_req_valid) {
            GlobalMemReq req{};
            req.id = sys->io_periph_req_bits_id;
            req.addr = sys->io_periph_req_bits_addr;
            req.write = sys->io_periph_req_bits_write;
            req.size = sys->io_periph_req_bits_size;
            req.wbe = sys->io_periph_req_bits_wbe;
            std::memcpy(req.wdata.data(), sys->io_periph_req_bits_wdata, MEM_BUS_WORDS * 4);
            out[0]->req = req;
        } else {
            out[0]->req = std::nullopt;
        }
    }

    void stage(uint64_t cycle, const std::vector<MemBusIn> &in) override {
        static constexpr int MEM_BUS_WORDS = MEM_BUS_WIDTH / 32;
        if ((int)in.size() != HARD_NUM_MC + 1) {
            std::cerr << "[Hard] stage: in vector size mismatch" << std::endl;
            std::abort();
        }

        // Drive MC response signals
        for (int mc = 0; mc < HARD_NUM_MC; ++mc) {
            auto &p = mem_ports[mc];
            if (in[mc + 1].resp) {
                auto &r = *in[mc + 1].resp;
                *p.resp_valid = 1;
                *p.resp_id = r.id;
                std::memcpy(p.resp_rdata, r.data.data(), MEM_BUS_WORDS * 4);
            } else {
                *p.resp_valid = 0;
            }
            *p.req_ready = in[mc + 1].reqAccepting ? 1 : 0;
        }
        // Drive peripheral response signals
        if (in[0].resp) {
            auto &r = *in[0].resp;
            sys->io_periph_resp_valid = 1;
            sys->io_periph_resp_bits_id = r.id;
            std::memcpy(sys->io_periph_resp_bits_rdata, r.data.data(), MEM_BUS_WORDS * 4);
        } else {
            sys->io_periph_resp_valid = 0;
        }
        sys->io_periph_req_ready = in[0].reqAccepting ? 1 : 0;

        // Negedge + eval so RTL settles with new resp / ready inputs.
        sys->clock = false;
        Verilated::timeInc(1);
        sys->eval();
    }

    void step(uint64_t cycle) override {
        // Posedge — commit Reg state.
        sys->clock = true;
        Verilated::timeInc(1);
        sys->eval();
    }
""")

    # printStats()
    f.write("    bool printStats(uint64_t, bool) override { return false; }\n")

    f.write("};\n")
