#!/usr/bin/env python3
"""Generate system_config.h from System.config.json and Verilator port accessors."""
import sys, os, json

config_json = sys.argv[1]  # Path to System.config.json
outdir = sys.argv[2]       # Output directory

with open(config_json) as f:
    cfg = json.load(f)

num_pu = cfg["numPU"]
num_mc = cfg["numMC"]
core = cfg["core"]

with open(os.path.join(outdir, "system_config.h"), "w") as f:
    f.write("// Auto-generated by gen_system_header.py — do not edit\n")
    f.write("#pragma once\n")
    f.write("#include <cstdint>\n\n")

    # CoreConfig struct
    f.write("struct CoreConfig {\n")
    f.write(f"    uint64_t initVec;\n")
    f.write(f"    int iCacheLines;\n")
    f.write(f"    int iCacheBlockSize;\n")
    f.write(f"    int iCacheAssoc;\n")
    f.write(f"    int memDst;\n")
    f.write(f"    int memTagBase;\n")
    f.write(f"    int memBusWidth;\n")
    f.write(f"    int numMemCtrl;\n")
    f.write(f"    uint64_t memCtrlSizes[{len(core['memCtrlSizes'])}];\n")
    f.write(f"    int scratchpadSize;\n")
    f.write(f"    bool useFPU;\n")
    f.write(f"    int pipeCnt;\n")
    f.write("};\n\n")

    # SystemConfig struct
    f.write("struct SystemConfig {\n")
    f.write("    int numMC;\n")
    f.write("    int numPU;\n")
    f.write("    CoreConfig core;\n")
    f.write("};\n\n")

    # Constant instance
    sizes = ", ".join(f"0x{int(s, 16):x}" if isinstance(s, str) else f"0x{s:x}" for s in core["memCtrlSizes"])
    init_vec = int(core["initVec"], 16) if isinstance(core["initVec"], str) else core["initVec"]

    f.write("inline constexpr SystemConfig SYSTEM_CONFIG = {\n")
    f.write(f"    .numMC = {num_mc},\n")
    f.write(f"    .numPU = {num_pu},\n")
    f.write(f"    .core = {{\n")
    f.write(f"        .initVec = 0x{init_vec:x},\n")
    f.write(f"        .iCacheLines = {core['iCacheLines']},\n")
    f.write(f"        .iCacheBlockSize = {core['iCacheBlockSize']},\n")
    f.write(f"        .iCacheAssoc = {core['iCacheAssoc']},\n")
    f.write(f"        .memDst = {core['memDst']},\n")
    f.write(f"        .memTagBase = {core['memTagBase']},\n")
    f.write(f"        .memBusWidth = {core['memBusWidth']},\n")
    f.write(f"        .numMemCtrl = {len(core['memCtrlSizes'])},\n")
    f.write(f"        .memCtrlSizes = {{{sizes}}},\n")
    f.write(f"        .scratchpadSize = {core['scratchpadSize']},\n")
    f.write(f"        .useFPU = {'true' if core['useFPU'] else 'false'},\n")
    f.write(f"        .pipeCnt = {core['pipeCnt']},\n")
    f.write(f"    }},\n")
    f.write("};\n\n")

    # Memory port accessors (same as gen_system_ports.py)
    f.write("// Verilator port accessors for MC memory interfaces\n")
    f.write("#define SYSTEM_MEM_PORT_CASES \\\n")
    for i in range(num_mc):
        f.write(f"    case {i}: "
                f"p.req_valid = &sys->io_mem_{i}_req_valid; "
                f"p.req_ready = &sys->io_mem_{i}_req_ready; "
                f"p.req_id = &sys->io_mem_{i}_req_bits_id; "
                f"p.req_addr = &sys->io_mem_{i}_req_bits_addr; "
                f"p.req_wdata = sys->io_mem_{i}_req_bits_wdata; "
                f"p.req_wbe = &sys->io_mem_{i}_req_bits_wbe; "
                f"p.req_write = &sys->io_mem_{i}_req_bits_write; "
                f"p.resp_valid = &sys->io_mem_{i}_resp_valid; "
                f"p.resp_id = &sys->io_mem_{i}_resp_bits_id; "
                f"p.resp_rdata = sys->io_mem_{i}_resp_bits_rdata; "
                f"break;")
        if i < num_mc - 1:
            f.write(" \\")
        f.write("\n")

    # PU core accessor for SPM preloading
    f.write("\n// Verilator PU core accessors for SPM preloading\n")
    f.write("#define SYSTEM_PU_CASE_ENTRIES \\\n")
    for i in range(1, num_pu + 1):
        f.write(f"    PU_CASE({i});")
        if i < num_pu:
            f.write(" \\")
        f.write("\n")
